### PR TITLE
Update Calico Ubuntu doc to use CNI plugin

### PR DESCRIPTION
**Pull request by caseydavenport**

### CODE REVIEW

**Comment by tomdee** [comment]
I'm done with this now, back to you.

**Comment by caseydavenport** [comment]
Did you make any comments? Or just the ones from the CoreOS doc?

**Comment by tomdee** [comment]
Ooops, wrong one. I meant I'm done with the coreos one

**Comment by tomdee** [comment]
OK, I've reviewed this now. Some of the CoreOS comments apply here too (e.g. linking to our docs in the NAT at the border router section) but I won't repeat them.

**Pull request merged**
